apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cpu-limit-no-request
  name: cpu-limit-no-request
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-limit-no-request
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cpu-limit-no-request
    spec:
      containers:
      - image: litmuschaos/stress-ng
        args:
          - --cpu=1
          - --timeout=200d
        imagePullPolicy: IfNotPresent
        name: cpu-limit-no-request
        resources:
          limits:
            cpu: 77m
            memory: 22Mi
          requests:
            cpu: 0m
            memory: 0Mi
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]