apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: init-container-pod
  name: init-container-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-container-pod
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: init-container-pod
    spec:
      initContainers:
      - name: init-container-55mi-mem
        image: litmuschaos/stress-ng
        args:
          - --vm-bytes=1G
          - --vm=1
          - --timeout=3m
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]
        resources:
          requests:
            cpu: 55m
            memory: 55Mi
          limits:
            cpu: 55m
            memory: 55Mi
      containers:
      - name: after-init-container
        image: nginxinc/nginx-unprivileged:stable-alpine
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
          limits:
            cpu: 10m
            memory: 10Mi
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]