apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memory-limit-no-request
  name: memory-limit-no-request
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memory-limit-no-request
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: memory-limit-no-request
    spec:
      containers:
      - image: litmuschaos/stress-ng
        args:
          - --vm-bytes=1G
          - --vm=1
        imagePullPolicy: IfNotPresent
        name: memory-limit-no-request
        resources:
          limits:
            cpu: 22m
            memory: 22Mi
          requests:
            cpu: 0m
            memory: 0Mi