apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: memory-limit-eq-request
  name: memory-limit-eq-request
spec:
  replicas: 2
  selector:
    matchLabels:
      app: memory-limit-eq-request
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: memory-limit-eq-request
    spec:
      containers:
      - image: litmuschaos/stress-ng
        args:
          - --vm-bytes=1G
          - --vm=1
        imagePullPolicy: IfNotPresent
        name: memory-limit-eq-request
        resources:
          requests:
            cpu: 22m
            memory: 22Mi
          limits:
            cpu: 22m
            memory: 22Mi
        image: nginx
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]            