apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: no-load-with-requests
  name: no-load-with-requests
spec:
  replicas: 2
  selector:
    matchLabels:
      app: no-load-with-requests
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: no-load-with-requests
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: no-load-with-requests
        resources:
          requests:
            cpu: 22m
            memory: 22Mi
          limits:
            cpu: 22m
            memory: 22Mi
        image: nginx
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop: ["ALL"]     
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: default-conf
          readOnly: true
      volumes:
      - name: default-conf
        configMap:
          name: nginx-echo
          items:
            - key: default.conf
              path: default.conf                   
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-echo
data:
  default.conf: |
    server {
        listen 8080;
        location / {
            default_type text/plain;
            expires -1;
            return 200 'Server address: $server_addr:$server_port\nServer name: $hostname\nDate: $time_local\nURI: $request_uri\nRequest ID: $request_id\nHost header: $Host\n';
        }
    }            